### PR TITLE
Update boards.txt

### PR DESCRIPTION
**Pull request by drid**
Add BMW F800GS LED turn signals repo

### CODE REVIEW

**Comment by kasbah** [comment]
Nice one. I checked it with https://kitspace.org/submit/ and it looks good to me so I'll merge now.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/gitlab.com/drid/f800gs-led-turn-signal/

- It couldn't get the Interactive BOM because the file was saved with a newer version of KiCad. Are you using a nightly build of KiCad?
- There's a problem with the README images from Gitlab, we are aware of this issue. If you want to work around it you can use absolute URLs for the images in the README (e.g. ``) 

Let me know if you see any other issues.

**Comment by drid** [comment]
Hi, thank you for adding this project
Yes I am using kicad nightly but I can generate the IBOM manually and add it to the repo.
Are updates pulled automatically?

**Comment by kasbah** [comment]
Updates are pulled automatically every 24 hours. I can manually make it update whenever though. The IBOM from your repo won't be displayed on Kitspace unfortunately, only the ones we generate from the .kicad_pcb (and we currently only do this for stable KiCad 5).

**Pull request merged**
