### PR TITLE
Add nerdyscout/NodeMCU

### PR DESCRIPTION
**Pull request by nerdyscout**

### CODE REVIEW

**Comment by kasbah** [comment]
It's up, but looks like there's an issue with identifying the copper layer. I'll take a look at this but a quick fix for now may be to leave off the `gerbers` field in the yaml. Kitspace will then plot the Gerbers itself from the KiCad file.

**Comment by kasbah** [comment]
Ah, just saw you recently renamed the layer, let's see how it fares when it re-builds in a second.

**Comment by nerdyscout** [comment]
thanks for your support.

one additional question:
the pictures are not shown on kitspace as it uses this path
https://raw.githubusercontent.com/nerdyscout/NodeMCU/master/tasmota_config_pis.png
instead of
https://raw.githubusercontent.com/nerdyscout/NodeMCU/master/PIS/tasmota_config_pis.png

is this some issue as it is an multi project? I am afraid of changing these urls as on github.com and github.io it is fine.

**Comment by kasbah** [comment]
Yeah, it's an issue on our end. Taking a look at it now.

**Comment by nerdyscout** [comment]
any news on this?

**Comment by kasbah** [comment]
No, not yet. It's more complicated than first thought because marky-markdown will already replace the URL with a full `https:///...` URL. After readme processing it's actually impossible to tell if the URL was supposed to point to a sub-folder. 

https://github.com/kitspace/kitspace/blob/master/tasks/page/makeReadme.js#L52-L64

We need to stop marky-markdown from replacing the URL, replace the URL before passing it to marky-markdown (messy) or fix it in marky-markdown.

**Comment by kasbah** [comment]
Fixed with 40b50b6 @nerdyscout !

**Pull request merged**
