### PR TITLE
Add aleksas/interferometer 

### PR DESCRIPTION
**Pull request by aleksas**
Add 3y old project circuit

### CODE REVIEW

**Comment by kasbah** [comment]
Ok, that's compatible now. There is not a lot of info in the 1-click-bom.tsv though. Will add more part information there?

Btw. is the intention to send a pull-request to @Kiogora to merge these changes or just keep a fork?

**Comment by kasbah** [comment]
It's up: https://kitspace.org/boards/github.com/aleksas/interferometer/

Looks like we doesn't yet recognize the "manuf#" heading, "Part Number" or "MPN" would work for sure.

**Comment by aleksas** [comment]
Actually with jlcpcb does better job at guessing picking part probably due too using footprint info. I've triedto do 1-click-bom but it only picked 5 parts out of >20.

**Comment by kasbah** [comment]
Good to know, thanks. Did you try the bom-builder too?

You can also add the JLC/LCSC part numbers to the Kitspace BOM (in a LCSC column) for future reference and easier buying for others.

**Comment by aleksas** [comment]
No I haven't tried bom-builder. Not realy sure how to get it or run it :/

**Comment by kasbah** [comment]
Oh, I sent you a link before to what I thought was your email: 
image.

**Comment by aleksas** [comment]
Ah yes, found your email. Sorry for confusion.

**Comment by Kiogora** [comment]
Please keep the fork. I shall archive the repository.

**Comment by aleksas** [comment]
@Kiogora can you provide more details on your project? Results?

**Comment by kasbah** [comment]
@aleksas, since you were asking in the chat about how often the site is updated, I just merged #252 and coupled it with a script running on a server that watches all projects for changes. It should now update 3-10 minutes after you make a change in your repo.

**Comment by aleksas** [comment]
Ok thanks. The other thing is part provider links like mouser, digikey and other on top of the project page indicate part number that is too high. Also if you follow the link, it shows components that are not part of the pcb. EasyEDA on the other hand shows proper list of parts.

**Comment by kasbah** [comment]
Cheers, regarding the parts, looks you updated the BOM and it's fixed now?

**Comment by aleksas** [comment]
Hi, not really. Board doesn't have a "FAN BLOWER" but it is added to the shopping list. I've cleaned up BOM from auto filled parts and rolled back to initial elements and only manually entered corresponding partnumbers for other part providers. If you check bom you'll notice that it doesn't have more that 6 parts per part provider, but the liks above show 9 for digikey and mouser.

**Comment by kasbah** [comment]
The reason is that the "R5, R6, R7, R8" line is 4 parts. I'll admit the UI is confusing the way it is and should probably be changed to count BOM lines rather than individual parts.

If you do notice any other issues please do open up tickets.

**Comment by aleksas** [comment]
Ok thanks for clearifying. Also sorry for confusion regarding "FAN BLOWER". Apparently I had items in my shopping cart from earlier experiments which caused listing too many components by digikey. It's ok now, thanks.

**Comment by aleksas** [comment]
@kasbah  Hi Kaspar, you should take down the interferometer. I had it made a while ago and it turned out to be designed poorly.
I'm working on a brand new version, don't know when that's ready.

**Comment by kasbah** [comment]
Alright, fair enough. I've removed it and added a re-direct to the archived Github repo (so any existing links to the kitspace project aren't completely broken).

**Pull request merged**
