### PR TITLE
Add singingplants

### PR DESCRIPTION
**Pull request by vektorious**
Added our plant moisture to sound and light sensor.

### CODE REVIEW

**Comment by kasbah** [comment]
Hi Alex, very nice. Right now if you want to use a .csv file you also have to add it to the kitspace.yaml

```yaml
bom: 1-click-bom.csv
```

**Comment by kasbah** [comment]
You probably also want to point it at the gerbers:

```yaml
gerbers: pcb/gerbers
```

**Comment by vektorious** [comment]
Dam,
I'm sorry. I even remember reading it in the instructions but I totally
forgot about it.

I updated my .yaml file and it should fine now.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/gitlab.com/alexander.kutschera/singingplants/

**Pull request merged**
