### PR TITLE
Add ESP8266_DS18B20

### PR DESCRIPTION
**Pull request by alpharesearch**

### CODE REVIEW

**Comment by kasbah** [comment]
Nice, [here is a preview](http://add-esp8266_ds18b20.preview.kitspace.org/boards/github.com/alpharesearch/ESP8266_DS18B20/). Look OK to you?

If you want to let people buy parts you should select some. You could use the [BOM Builder](https://bom-builder.kitspace.org).

**Comment by alpharesearch** [comment]
Thanks, yes looks good. Most parts are optional this is just a little breakout board for the esp8266. I just used parts that I had already at home. With the little prototyping area it allows to add different little projects. For example I have a some boards connected to Smartthings hub. Right now I'm using 3 versions, log 5 temperatures, red and green status LED, press two buttons on bed remote control. 
Markus

**Comment by alpharesearch** [comment]
When I make changes to the readme file on github will your site automatically fetch the change?

**Comment by kasbah** [comment]
[Here it is](https://kitspace.org/boards/github.com/alpharesearch/esp8266_ds18b20/)! I would encourage you to at least select some manufacturer part numbers for the BOM. The page, including all the files, BOM and readme, will update every 24 hours at minimum (more if there are new projects or I press re-build for another reason). You can see the builds [here](https://travis-ci.org/kitspace/kitspace).

**Comment by alpharesearch** [comment]
Ok, I will do update the BOM for the most important parts over the weekend. Thanks.

**Pull request merged**
