### PR TITLE
Add  aleksas/interferometer 

### PR DESCRIPTION
**Pull request by aleksas**
Add repo

### CODE REVIEW

**Comment by kasbah** [comment]
Hello, `kitspace.yaml` has to be at the root of your repository (and not just be the example `kitspace.yaml`) .

**Comment by aleksas** [comment]
Just moved to root.
Now KiCad files are under Design folder. Is that ok?

**Comment by kasbah** [comment]
That's better yes. [bom.csv](https://github.com/aleksas/interferometer/blob/master/bom.csv) doesn't have all the needed info though. I can give you access to the [bom-builder](https://kitspace.org/bom-builder) tool to help with that if you want.

**Comment by kasbah** [comment]
I sent you a BOM Builder access to your gscoder email address.

**Comment by kasbah** [comment]
Ok, so the remaining issues are:

1. The kitspace.yaml isn't pointing at the bom.csv
2. The bom.csv isn't in a format that's expected

**Comment by kasbah** [comment]
Closing in favor of #251

**Pull request closed without merging**
