### PR TITLE
Add Aquarius

### PR DESCRIPTION
**Pull request by LincolnUehara**

### CODE REVIEW

**Comment by kasbah** [comment]
Looks nice. I emailed you a URL to the BOM builder, if you want to use it to improve the BOM.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/lincolnuehara/aquarius/

We need to fix the image processing (probably related to #193). Sorry about that. In the meantime if you change the URLs to the raw ones it will work e.g. 

https://raw.githubusercontent.com/LincolnUehara/Aquarius/master/img/main.jpg

P.S. Did you mean randomly by "randomically"?

**Comment by LincolnUehara** [comment]
Hi! Thanks for all the help!

Yeah, I have suspected at first glance that the broken images were due to html markup that I had put on README. So, I will maintain that to you guys could debug it and so on.

P.S. Yeah, "randomically" o/
I was sleepy and forgot the english word, and the first thing dictionary returned was "randomly"...
It's quite odd, but [looks like "randomically" is not natural word](https://english.stackexchange.com/questions/83611/what-does-randomically-mean) :astonished:

**Comment by kasbah** [comment]
Images are now fixed.

**Comment by LincolnUehara** [comment]
Thanks!!!

**Pull request merged**
