### PR TITLE
Added openbadge

### PR DESCRIPTION
**Pull request by patcon**
If the others support this idea, we'll use the source repo :) Thanks Kaspar!

### CODE REVIEW

**Comment by kasbah** [comment]
Nice, looking good. The `.yml` needs to be `.yaml` currently, it's not actually being picked up yet.

**Comment by kasbah** [comment]
Fixed it in Kitspace with e9601331babd11abd45630799641419d67d134de (I think).

**Comment by patcon** [comment]
Fix on my end too! Ready for merge

**Comment by patcon** [comment]
couple more places to update maybe? https://github.com/kitspace/kitspace/blob/829bed06ba2b29813f3958009cfc88edfa288d6a/tasks/page/processBOM.js#L53-L56

**Comment by kasbah** [comment]
[Here is a preview](http://add-openbadge.preview.kitspace.org/boards/github.com/patcon/openbadge/). It's not understanding your naming convention for the Gerbers unfortunately. I think you are using the newest Eagle convention which should be recognized. Could you [open an issue with tracespace](https://github.com/tracespace/tracespace/issues) please?

> couple more places to update maybe? 

You are linking an old commit. Looks fine [on master](https://github.com/kitspace/kitspace/blob/master/tasks/page/processBOM.js#L53-L56).

**Comment by kasbah** [comment]
Because it wasn't reading the `kitspace.yml` before it just had a guess at which Gerbers you wanted  and those rendered fine (presumably an older export). Try it again now. This is definitely something that needs to be fixed in [tracespace/whats-that-gerber](https://github.com/tracespace/tracespace/tree/next/packages/whats-that-gerber).

**Comment by kasbah** [comment]
Do you have any idea what convention or CAM job these files are using? Is this a custom job?

**Comment by patcon** [comment]
cc @OrenLederman

**Comment by OrenLederman** [comment]
@patcon I'll try to add the yup file today/tomorrow to the root directly. You can open an issue or crate a pull request if you like :)

**Comment by kasbah** [comment]
Specifically the ones in `eagle/nRF_badge/Badge_03_v6/export_20180201`.

**Comment by OrenLederman** [comment]
I exported them from Eagle, and I'm pretty sure I used a variation of a CAM file that was based on PCB.ng's CAM file (https://support.pcb.ng/support/solutions/articles/9000075420-for-eagle-users )

**Comment by kasbah** [comment]
Seems this branch is now in a strange state after I tried updating it. @patcon if you still want to add this, please open another pull request. The gerber rendering issues should be resolved by now.

**Pull request closed without merging**
