### PR TITLE
Adding balthazar-space keyboard

### PR DESCRIPTION
**Pull request by goran-mahovlic**
Hi, I am helping balthazar team on some projects, and I think the would be great fit on kitspace.

### CODE REVIEW

**Comment by kasbah** [comment]
Thanks, it's up! https://kitspace.org/boards/github.com/balthazar-space/balthazarkeyboard3/

**Comment by goran-mahovlic** [comment]
> Thanks, it's up! https://kitspace.org/boards/github.com/balthazar-space/balthazarkeyboard3/

Great! Thank you! I have just refreshed parts, as I did not notice that part are from ULX3S :)

**Comment by kasbah** [comment]
Oops, I didn't notice either. Will take 40 mins to update unfortunately.

**Comment by goran-mahovlic** [comment]
40 min is fine, Tomorow I will try to add two more remaining boards.

**Pull request merged**
