### PR TITLE
Added Neotron 32

### PR DESCRIPTION
**Pull request by thejpster**

### CODE REVIEW

**Comment by kasbah** [comment]
Looks great! Are you sure you want to use a separate repo? You could use the kicad files directly in the other repo instead:

```yaml
eda: 
  type: kicad
  pcb: neotron-32.kicad_pcb
```

**Comment by thejpster** [comment]
Good point!

**Comment by thejpster** [comment]
TBF, it wasn't obvious I could do this when going through https://kitspace.org/submit/.

**Comment by kasbah** [comment]
In case you missed it @thejpster. I sent a PR to add the BOM as it won't work without it. https://github.com/Neotron-Compute/Neotron-32-Hardware/pull/24

**Comment by thejpster** [comment]
I've merged the BOM. Can you kick travis or should I push a dummy change to the PR?

**Comment by kasbah** [comment]
Oh no, looks like there is an issue with the KiCad rendering. Will fix this in the morning. 

https://kitspace.org/boards/github.com/Neotron-Compute/Neotron-32-Hardware/

**Comment by thejpster** [comment]
Thanks!

**Comment by kasbah** [comment]
Sorry for the delay, fixed (or rather worked around) with #268

**Pull request merged**
