### PR TITLE
Adding ulx4m board

### PR DESCRIPTION
**Pull request by goran-mahovlic**

### CODE REVIEW

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/intergalaktik/ulx4m/

**Comment by goran-mahovlic** [comment]
> It's up! https://kitspace.org/boards/github.com/intergalaktik/ulx4m/

Thanks a lot!

**Comment by goran-mahovlic** [comment]
I see small problem.

This is showing older board version so I do not know how it is created and what can I do to get V002 https://kitspace.org/interactive_bom/?github.com/intergalaktik/ulx4m

**Comment by kasbah** [comment]
FYI I proposed a fix to that issue here: https://github.com/intergalaktik/ulx4m/pull/2

**Comment by goran-mahovlic** [comment]
Thank you!

**Pull request merged**
