### PR TITLE
Add Open-Gamma-Project/Mini-SiD

### PR DESCRIPTION
**Pull request by Phoenix1747**
Hello again 👋🏻

### CODE REVIEW

**Comment by kasbah** [comment]
Hi, it's up! https://kitspace.org/boards/github.com/open-gamma-project/mini-sid/

Looks great, except that there's an issue with the Gerber preview that I'll need to look into.

**Comment by Phoenix1747** [comment]
Yes, I noticed that too. Looks good on any other Gerber viewer I tried, though.

**Comment by kasbah** [comment]
The issue is that the arc and the line in the outline don't use the same point at the bottom. The distance between them is greater than our threshold (currently 1.27mm). I don't think the way Tracespace (our gerber renderer) determines the outline is ideal but it's what we have at the moment. 

I can increase the threshold to what's required (9mm) but it may cause problems with other boards (testing it out now) or you could line up these points. 



image

**Comment by Phoenix1747** [comment]
Should be fixed now!
https://github.com/Open-Gamma-Project/Mini-SiD/commit/7f61b85327134a984c67467492568289e508d004

**Comment by kasbah** [comment]
Great, thanks, it's been updated.

**Pull request merged**
