### PR TITLE
Add Glasgow Rev C1

### PR DESCRIPTION
**Pull request by John-K**
Forked upstream GlasgowEmbedded/glasgow to add kitspace.yml

### CODE REVIEW

**Comment by kasbah** [comment]
Hi, looks good to me. Is the intention to add the original (@whitequark) or maintain a fork?

**Comment by John-K** [comment]
How about I submit a patch upstream and issue a follow-up PR to Kitespace
if and when it’s merged?

**Comment by kasbah** [comment]
Sounds good to me.

**Comment by John-K** [comment]
@kasbah Can we approve this PR in the meantime? I'd like to use Kitspace to build this PCB

**Comment by John-K** [comment]
@kasbah is it possible to use the `multi:` interface with just one board to start? The Glasgow maintainers would prefer this to facilitate maintaining the yaml for future releases.

**Comment by kasbah** [comment]
Yep, you can use `multi` with just one board.

**Comment by John-K** [comment]
Working with Glasgow maintainers to upstream this change now, will submit a new PR soon

**Pull request closed without merging**
