### PR TITLE
rough draft: adding pcbshopper link, response to issue 155

### PR DESCRIPTION
**Pull request by evanyang1**
I added a PCB Shopper link to the right of the other links. Although this is a rough draft and this layout is not final, this is a major step towards that direction, and further discussion on Issue #155 can be made.

### CODE REVIEW

**Comment by kasbah** [comment]
You are including changes to package.json, lockfiles and a binary copy of ninja here. Please remove them ([it's actually breaking CI](https://travis-ci.org/kitspace/kitspace/builds/529553029#L854)). 

You know layout we are working towards, so not much to discuss until you get closer to that?

**Comment by evanyang1** [comment]
Should `package.json` and `package-lock.json` be added to .gitignore?

**Comment by kasbah** [comment]
package.json definitely not. could add package-lock.json but it shouldn't be generated since you should use `yarn` not `npm` (this was clarified in readme recently).

**Comment by kasbah** [comment]
Pcbshopper link was added with #198.

**Pull request closed without merging**
