### PR TITLE
Added kit for David Watt's binary crap clock.

### PR DESCRIPTION
**Pull request by MobiusHorizons**

### CODE REVIEW

**Comment by MobiusHorizons** [comment]
The CI has failed, but as far as I can tell, that's because the build is broken (couldn't install yarn), not because of my code. let me know if I should do anything else.

**Comment by kasbah** [comment]
Thanks for this. Yeah, this looks good on kitspace.org/submit. I need to fix the build. 

Also interesting to see that youtube embeds work on kitspace but not on github.

**Comment by kasbah** [comment]
Hey, I fixed the build. I think you are missing a drill file: http://add-binary-crap-clock-kit.preview.kitspace.org/boards/github.com/MobiusHorizons/binary-crap-clock-kit/

**Comment by MobiusHorizons** [comment]
I have now updated my repo. let me know if I need to do anything else.

Thanks

**Comment by kasbah** [comment]
Hey, did you see this message? https://github.com/MobiusHorizons/binary-crap-clock-kit/commit/42d7e385f02c7771e2804d1cd1cfb0b9d1629cc2#commitcomment-28768859

**Comment by kasbah** [comment]
Closing this till https://github.com/MobiusHorizons/binary-crap-clock-kit/pull/1 is merged.

**Pull request closed without merging**
