### PR TITLE
Add Falcon-Badge

### PR DESCRIPTION
**Pull request by saadcaffeine**
forked from securehardware-bi0s/Falcon-Badge

### CODE REVIEW

**Comment by kasbah** [comment]
Hello! Is the intention to add your fork or to add the main repo? Either way, as it stands it can't be added because 

- We need some sort of bill-of-materials. This can be a csv, excel or ods file (or even a .kicad_pcb).
- The gerbers and drill files need to be in the same folder
- It needs a kitspace.yaml file which points at theses:

```yaml
gerbers: path/to/gerbers
bom: path/to/bom-file.csv
```

**Comment by saadcaffeine** [comment]
Understood. Will be adding these

**Comment by kasbah** [comment]
If you think it would help for the BOM, I can give you access to [bom-builder](https://kitspace.org/bom-builder/), email me: kaspar@kitspace.org

**Comment by kasbah** [comment]
Closing for now, feel free to open a new request if someone wants to add this project.

**Pull request closed without merging**
