### PR TITLE
Add AFBR-SiPM-Carrier-Board

### PR DESCRIPTION
**Pull request by Phoenix1747**
New repo, new hardware :)

### CODE REVIEW

**Comment by Phoenix1747** [comment]
Just had a look at kitspace and it doesn't seem like the site updated. Actually I even get an error message saying "Page Not Found". Something wrong with my files?

Screenshot 2022-10-01 at 20-52-42 Page Not Found

**Comment by kasbah** [comment]
Yeah, sorry, having some trouble with the newly released KiCad 6.0.8 that's holding things up. (TIL you can't grab an older version from an Ubuntu PPA.)

**Comment by kasbah** [comment]
I've managed to downgrade KiCad to 6.0.2. It's up now: http://downgrade-kicad.preview.kitspace.org/boards/github.com/Open-Gamma-Project/AFBR-SiPM-Carrier-Board/

**Comment by Phoenix1747** [comment]
Works now, thanks!

**Pull request merged**
