### PR TITLE
Add astrohat project

### PR DESCRIPTION
**Pull request by ppapadeas**
Add astrohat project

### CODE REVIEW

**Comment by kasbah** [comment]
Hey, looks great. Do you want access to the [bom-builder](https://kitspace.org/bom-builder/) to improve the BOM?

**Comment by ppapadeas** [comment]
> Hey, looks great. Do you want access to the [bom-builder](https://kitspace.org/bom-builder/) to improve the BOM?

That would be nice!

**Comment by kasbah** [comment]
Alright, I sent you an email. I'll merge this as is for now. It will update every 24 hours. If you change the BOM, reply on here and I'll make it update sooner.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/gitlab.com/pierros/astrohat/

**Pull request merged**
