### PR TITLE
Add darling to project list

### PR DESCRIPTION
**Pull request by XenGi**
I added the `kitspace.yml` file and `bom.tsv` to my repo but kitspace seems to have trouble with my `README.md` file.

### CODE REVIEW

**Comment by kasbah** [comment]
Looks fine in [the preview](http://add-darling.preview.kitspace.org/boards/gitlab.com/XenGi/darling/). The readme render in the /submit guide thing works slightly differently unfortunately, I'll open an issue to look into it.

You see any issues in the preview?

**Comment by kasbah** [comment]
Looks like the table doesn't work. I'll open an issue for that too.

**Comment by kasbah** [comment]
Merging ;)

**Comment by XenGi** [comment]
Looks nice. Thx! Very cool project btw! :D

**Pull request merged**
