### PR TITLE
Trace space link

### LINKED ISSUE #165: Add an "inspect gerbers" link to tracespace
@mcous' tracespace viewer can now grab board files from the web so we can add direct links to send files across e.g. https://tracespace.io/view/?boardUrl=https://kitspace.org/boards/github.com/8bitmixtape/mcore_mixtape/mCore_Mixtape-8b12158-gerbers.zip

This should be a button near the rendering on the pages that says something like  "inspect gerbers with tracespace".

### PR DESCRIPTION
**Pull request by ollyoid**
closes #165

### CODE REVIEW

**Comment by kasbah** [comment]
Looks pretty good, preview is here: http://trace-space-link.preview.kitspace.org/boards/github.com/kitspace-forks/Bus_Pirate/

- Can we add a tracespace logo somewhere? 
- Would it be hard to overlay the whole section, making it a bit darker and saying there "inspect gerbers using tracespace viewer" or something similar?

**Comment by ollyoid** [comment]
So instead of having external link icon use the trace space one? 
And, when you say to make it darker you mean when you hover over it right?

**Comment by ollyoid** [comment]
Something like that? I know it's ugly any suggestions for better layout.

**Comment by kasbah** [comment]
Yeah, like that but nicer. Maybe also just put the logo with the text and let it appear only when you hover. I think the wording should be "Inspect Gerber files with Tracespace".

**Comment by kasbah** [comment]
Will you continue with this @ollyoid or should someone take it over?

**Pull request merged**
