### PR TITLE
Add partycat lighting controller

### PR DESCRIPTION
**Pull request by lukecyca**
Adding partycat lighting controller

### CODE REVIEW

**Comment by kasbah** [comment]
Nice one lukecyca, we definitely need more partycats. I can see, even before the build finishes, that it will complain that you don't have a README. It would be great if you could add one and put one or two sentences in there describing your project.

**Comment by lukecyca** [comment]
Thanks @kasbah. Just wanted to get this up and included ASAP.

I will add a README and license right away. Also preparing a youtube video, blog post, etc.

**Comment by kasbah** [comment]
Ok, reply here when you add a basic README please so I can run the preview build.

**Comment by lukecyca** [comment]
Done.

**Comment by kasbah** [comment]
Here is a preview: http://add-partycat.preview.kitnic.it/boards/github.com/lukecyca/partycat/

- Looks like the website link went wrong a bit
- There are no retailer SKUs at all specified in the 1-click-bom.tsv

**Comment by kasbah** [comment]
Just realised what's going on with the link.

If you add a kitnic.yaml with:

```yaml
description: ESP8266 + WS2812 controller
site: https://talk.vanhack.ca/t/esp8266-ws2812-partycat-controller/5129
```
Then the builder will make more sense of it. You could also choose a color for the rendering that is more party-ful if you wish. E.g. `color: orange` or `color: black`.

**Comment by lukecyca** [comment]
I've added a `kitnic.yml`. Will it regenerate [this page](http://add-partycat.preview.kitnic.it/boards/github.com/lukecyca/partycat/) automatically?

I also added some digikey part numbers to the BOM. For the passives I suppose I could just pick some arbitrarily? The ESP-12 isn't available from Digikey. There is an ESP-12E which would work I think. Sorry, still getting a feel for how to do BOMs. :)

**Comment by kasbah** [comment]
No, I have to press a button unfortunately. It's re-built now though. For parts that are not available just leave them blank and maybe say in the description where best to get them. Would be good if you could check if the 12E is suitable.

If you tweak the descriptions you can get 1-click BOM to fill out the generics and parts for which you know the MPNs. See [completion section in the README](https://github.com/monostable/1clickBOM#completion). I ran a quick auto-complete (the actual parts still need to be checked):

https://kaspar.h1x.com/partycat-1-click-bom.tsv

**Comment by kasbah** [comment]
ping @lukecyca

**Comment by kasbah** [comment]
You can now preview your submission yourself with [kitnic.it/submit/](https://kitnic.it/submit/)!

**Comment by kasbah** [comment]
ping @lukecyca

**Comment by kasbah** [comment]
Closing this until https://github.com/lukecyca/partycat/pull/2 is merged.

**Pull request closed without merging**
