### PR TITLE
Add Firefly board

### PR DESCRIPTION
**Pull request by goran-mahovlic**

### CODE REVIEW

**Comment by kasbah** [comment]
Hey, thanks for adding. Looks like there is a problem with our Gerber to SVG lib. Will take a look when I get a chance.

**Comment by goran-mahovlic** [comment]
> Hey, thanks for adding. Looks like there is a problem with our Gerber to SVG lib. Will take a look when I get a chance.

No problem, let me know if I need to fix something on my side.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/intergalaktik/firefly/

**Comment by goran-mahovlic** [comment]
> It's up! https://kitspace.org/boards/github.com/intergalaktik/firefly/

Thank you! I will add more info on git next month.

**Pull request merged**
