### PR TITLE
Add infidel sensor repo

### PR DESCRIPTION
**Pull request by darigovresearch**

### CODE REVIEW

**Comment by kasbah** [comment]
Here's a preview: http://add-infidel.preview.kitspace.org/boards/github.com/darigovresearch/infidel-sensor/

You titled this PR "test" and the repo is a fork, what's the intention? Should I merge this or wait to put up the main repo?

**Comment by darigovresearch** [comment]
Yes the plan was to test the process with our fork of the project to ensure everything was going well before merging a pull request to the main repository and switching out the source repository to be the main one, see here - https://github.com/drspangle/infidel-sensor/issues/19

When clicking the PCB supplier links they all give an error, is this because it's the test URL and not a merged one?

**Comment by kasbah** [comment]
Ok great, I'll wait to add it till it's on the main repo. Yes, those PCB links will start working once it's on the main Kitspace site.

**Comment by darigovresearch** [comment]
Thanks for the help @kasbah, the pull request has been merged & this pull request has been updated with the relevant URL 

See - https://github.com/drspangle/infidel-sensor/pull/23

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/drspangle/infidel-sensor/

**Pull request merged**
