### PR TITLE
Add Linux PCB badge

### PR DESCRIPTION
**Pull request by Chromico**
The project does not have a BOM at it's mostly a PCB and the brooch is optional.

### CODE REVIEW

**Comment by kasbah** [comment]
Ah, I'm not sure we can handle no-component projects yet. Could you try adding an empty `1-click-bom.tsv` file to the root of the project and we can see what happens on Travis CI?

**Comment by Chromico** [comment]
Yeah sure, hold on

**Comment by Chromico** [comment]
Already added the empty 1-click-bom.tsv to my main repo, can you check if everything is good?

**Comment by kasbah** [comment]
Looks like it can't deal with an empty BOM. I added the brooch pin with just a description with the link: https://github.com/Chromico/linux-penguin-PCB-badge/pull/2

**Comment by Chromico** [comment]
Merged your pull request, will it work now?

**Comment by Chromico** [comment]
Seems like Travis CI completed with no issues :)

**Comment by kasbah** [comment]
It's up! Looks nice. :penguin:  https://kitspace.org/boards/github.com/chromico/linux-penguin-pcb-badge/

**Pull request merged**
