### PR TITLE
Add OpenXenium project

### PR DESCRIPTION
**Pull request by Ryzee119**

### CODE REVIEW

**Comment by kasbah** [comment]
Hey thanks for adding. You need to add a `kitspace.yaml` file to your repo so we can find everything we need. 

https://github.com/kitspace/kitspace#kitspaceyaml-format

**Comment by Ryzee119** [comment]
Added :) (It was just in another test branch)

**Comment by kasbah** [comment]
Ah great, we currently need it on the master branch unfortunately. If you ever want to test something like this out in the future you could make a fork repository.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/ryzee119/openxenium/

**Pull request merged**
